[target.thumbv7em-none-eabihf]
rustflags = [
  # TODO: Where is this from?
  "-C",
  "link-arg=--nmagic",
  # For cortex-m-rt
  "-C",
  "link-arg=-Tlink.x",
  # For defmt 
  "-C",
  "link-arg=-Tdefmt.x",
]


[build]
# We compile without atomics, because its faster than using atomic trap handler
target = "thumbv7em-none-eabihf"

[unstable]
build-std = ["core", "alloc"]

[env]
# You can override this via environment variable when building or by changing it here
DEFMT_LOG = "trace"
